# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userlanguageprofile_is_learning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguageprofile',
            name='is_learning',
        ),
        migrations.AddField(
            model_name='userlanguageprofile',
            name='learning',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=3, null=True),
        ),
    ]
