# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20160312_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguageprofile',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userlanguageprofile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlanguageprofile',
            name='learning',
            field=models.IntegerField(blank=True, choices=[(1, 'Know'), (2, 'Proficient'), (3, 'Learning')], default=3, null=True),
        ),
    ]
